config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    post 'areas/download' => 'areas#download'
    post 'areas/upload' => 'areas#upload'
    post 'zones/download' => 'zones#download'
    post 'zones/upload' => 'zones#upload'
    post 'visits/download' => 'visits#download'
    post 'visits/upload' => 'visits#upload'
    post 'pedidos/download' => 'pedidos#download'
    post 'pedidos/upload' => 'pedidos#upload'
    post 'people/download' => 'people#download'
    post 'people/upload' => 'people#upload'
    post '2.0/personas' => 'people#list'
    post '2.0/persona' => 'people#get'
    post '2.0/visitas' => 'visits#list'
    post '2.0/visita' => 'visits#get'
  end

  resources :notificaciones
  resources :auditoria
  resources :users
  resources :areas
  root 'mapa#index'

  get 'acceso_denegado', to: redirect('/401.html')
  get 'falta_confirmacion', to: redirect('/falta_confirmacion.html')

  get 'common/update_zonas_filter', as: 'update_zonas_filter'
  get 'common/update_personas', as: 'update_personas'
  get 'common/update_pedidos_pendientes', as: 'update_pedidos_pendientes'
  get 'common/edit_pedido_modal/:id' => 'common#edit_pedido_modal', as: 'edit_pedido_modal'


  get 'people/update_zonas', as: 'update_zonas'

  # No existe en el código el dataAccess relacionado
  # post 'visits/mobRecibirVisitasDesde' => 'visits#mobRecibirVisitasDesde'

  get 'visits/getDireccion' => 'visits#getDireccion'
  get 'visits/getCoordenadas' => 'visits#getCoordenadas'

  get 'mapa/mostrar' => 'mapa#mostrar'
  get 'mapa/mobMapaPersonas' => 'mapa#mobMapaPersonas'

  resources :visits
  resources :people
  resources :zones
  resources :mapa
  resources :pedidos
  resources :departamentos
  resources :estados
  resources :instituciones
  resources :eventos

  get 'informes' => 'informes#index'
  get 'informes/voluntarios' => 'informes#voluntarios'
  get 'informes/personas' => 'informes#personas'
  get 'informes/cumpleanios' => 'informes#cumpleanios'
  get 'informes/visitas' => 'informes#visitas'
end

app/models/visit.rb
class Visit < ApplicationRecord

  belongs_to :person
  belongs_to :state

  validates :fecha, presence: true
  validate :fecha_must_in_the_past

  #geocoded_by :direccion, :latitude  => :latitud, :longitude => :longitud
  reverse_geocoded_by :latitud, :longitud, :address => :direccion
  after_validation :reverse_geocode

  def fecha_must_in_the_past
    if fecha.present? && fecha.to_datetime > DateTime.now + 1.day
      errors.add(:fecha, "no pueda ser futura")
    end
  end

  self.per_page = 20

  filterrific(
    available_filters: [
      :search_query,
      :with_area_id,
      :with_zone_id,
      :with_estado_id,
      :with_departamento_id,
      :with_person_id,
      :fecha_gte,
      :visitas
    ]
  )

  scope :search_query, lambda { |query|
	return nil  if query.blank?

	# condition query, parse into individual keywords
	terms = query.to_s.downcase.split(/\s+/)

	# replace "*" with "%" for wildcard searches,
	# append '%', remove duplicate '%'s
	terms = terms.map { |e|
	(e.gsub('*', '%') + '%').gsub(/%+/, '%')
	}
	# configure number of OR conditions for provision
	# of interpolation arguments. Adjust this if you
	# change the number of OR conditions.
	num_or_conds = 1

	joins(:person).where(
	terms.map { |term|
	  "(LOWER(people.nombre) LIKE ?)"
	}.join(' AND '),
	*terms.map { |e| [e] * num_or_conds }.flatten
	)
  }

  scope :with_area_id, lambda { |area_id|
	joins(person: [{zone: :area}]).where("areas.id = ?", area_id)
  }

  scope :with_zone_id, lambda { |zone_id|
	joins(person: :zone).where("zones.id = ?", zone_id)
  }

  scope :with_person_id, lambda { |person_id|
	joins(:person).where("people.id = ?", person_id)
  }

  scope :with_estado_id, lambda { |estado_ids|
    joins(:person).where(people: {estado_id: [*estado_ids]})
  }

  scope :with_departamento_id, lambda { |departamento_ids|
    return nil if departamento_ids.all? &:blank?
    joins(person: [:departamentos]).where(departamentos: {id: [*departamento_ids]}).uniq
  }


  scope :activas, -> { where.not(state_id: 3).order(fecha: :desc, id: :desc) }

  scope :fecha_gte, lambda { |reference_time|
    return nil if reference_time.blank?
    where('visits.fecha >= ?', reference_time.to_datetime.in_time_zone('Moscow').to_s)
  }

  #TODO renombrar a informe
  scope :visitas, lambda { |area_id = nil|
    if area_id.blank?
      Visit.joins(person: [{zone: :area}]).group("zones.id", "areas.id").select("zones.nombre as zona_nombre", "areas.nombre as area_nombre", "COUNT(DISTINCT visits.id) as count")
    else
      Visit.joins(person: [{zone: :area}]).where("areas.id = ?", area_id).group("zones.id", "areas.id").select("zones.nombre as zona_nombre", "areas.nombre as area_nombre", "COUNT(DISTINCT visits.id) as count")
    end
  }

  def getDescripcionAuditoria
    return "Persona: #{person.nombre if !person.nil?} Fecha: #{fecha.to_date()} Descripción: #{descripcion}"
  end

end

app/controllers/api/visits_controller.rb
class Api::VisitsController < Api::ApiController
  before_action :authenticate_user!
  before_action :invitado

  def download
    respuesta = VisitDataAccess.download params['datos'], params['fecha']
    render :json => respuesta
  end

  def upload
    respuesta = VisitDataAccess.upload current_user, params['datos'], params['fecha']
    render :json => respuesta
  end

  def list
    respuesta = VisitDataAccess.list
    render :json => respuesta
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_action :puede_crear_visita, only: [:create]
  before_action :puede_editar_visita, only: [:update]
  before_action :puede_borrar_visita, only: [:destroy]

  def getDireccion
    direccion = Geocoder.search(params['lat'] + "," + params['lng'])
    if direccion.first
      render :plain => direccion.first.address
    else
      render :plain => ''
    end
  end

  def getCoordenadas
    render :json => Geocoder.coordinates(params['direccion'])
  end

  # No existe en código el dataAccess asociado
  # def mobRecibirVisitasDesde
  #   respuesta = VisitDataAccess.getVisitasDesde params['datos'], params['fecha']
  #
  #   render :json => respuesta
  # end

  # GET /visits
  # GET /visits.json
  def index
    if (params[:person_id])
      if !params[:filterrific]
        params[:filterrific] = Hash.new
      end
      params[:filterrific][:with_person_id] = params[:person_id]
    else
      session["visits#index"] = nil
    end

    @filterrific = initialize_filterrific(
      Visit,
      params[:filterrific],
      select_options: {
        with_area_id: Area.options_for_select,
        with_zone_id: Zone.options_for_select,
        with_estado_id: Estado.options_for_select,
        with_departamento_id: Departamento.options_for_select
      },
      default_filter_params: {}
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @visits = @filterrific.find.includes(:person).activas.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
    @visit.fecha = Time.now

    if (params[:person_id])
      @visit.person_id = params[:person_id]
      ubicacion = PersonDataAccess.getUbicacionUltVisita(params[:person_id])
      if ubicacion
        @visit.latitud = ubicacion.latitud
        @visit.longitud = ubicacion.longitud
      else
        @visit.latitud = -34.6425867
        @visit.longitud = -58.5659176
      end
    end
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    @visit.state = State.find_by_nombre('Actualizado');

    respond_to do |format|
      if @visit.save
        AuditoriaDataAccess.log current_user, Auditoria::ALTA, Auditoria::VISITA, @visit
        format.html { redirect_to visits_url(nil, person_id: @visit.person_id), notice: 'Visita creada correctamente.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        AuditoriaDataAccess.log current_user, Auditoria::MODIFICACION, Auditoria::VISITA, @visit
        format.html { redirect_to visits_url(nil, person_id: @visit.person_id), notice: 'Visita actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        params[:person_id] = @visit.person_id
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    VisitDataAccess.borrar_logico(@visit, current_user)
    respond_to do |format|
      format.html { redirect_to visits_url(:person_id => params[:person_id]), notice: 'Visita borrada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:descripcion, :fecha, :person_id, :latitud, :longitud)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<% puede_editar ||= false %>
<% disabled = !puede_editar %>

<%= form_for(@visit, :html => {:class => 'col s12'})  do |f| %>
  <%= render 'shared/errors', obj: @visit %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.collection_select :person_id, Person.activas, :id, :nombre, {:include_blank => true}, {:disabled => disabled} %>
      <%= f.label :person_id, "Persona", class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :fecha, class: "datepicker", :disabled => disabled %>
      <%= f.label :fecha, class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_area :descripcion, class:"materialize-textarea", :disabled => disabled %>
      <%= f.label :descripcion, 'Comentario', class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :direccion, :disabled => disabled %>
      <%= f.label :direccion, 'Dirección', class: "active" %>
    </div>
  </div>

  <div class="row">
    <% if !Rails.env.production? %>
      <div class="input-field col s6">
        <%= f.text_field :latitud, :disabled => disabled %>
        <%= f.label :latitud, class: "active" %>
      </div>
      <div class="input-field col s6">
        <%= f.text_field :longitud, :disabled => disabled %>
        <%= f.label :longitud, class: "active" %>
      </div>
    <% else %>
      <%= f.hidden_field :latitud, :disabled => disabled %>
      <%= f.hidden_field :longitud, :disabled => disabled %>
    <% end %>
  </div>

  <%= render 'shared/pedidosPersona', selectorPersona: "visit_person_id" %>

  <div class="form-group">
    <%= f.label 'Ubicación', class: "col-md-1 control-label", for: "googleMapVisita" %>
    <div class="col-md-10">
      <div id="googleMapVisita" class="mapaUbicacionZona"></div>
    </div>
  </div>

  <%= render 'layouts/buttons_submit', path: visits_path(nil, :person_id => params[:person_id]), f: f, remote: false, mostrar_aceptar: !disabled %>

<% end %>

<%= render 'pedidos/modals', selectorPersona: "visit_person_id" %>

<% if disabled %>
  <div id="mapDisabled"></div>
<% end %>

 <script defer>
  loadMapaScript('cargarUbicacionVisita');
 </script>

app/views/visits/_list.html.erb
<div id="filterrific_results">

  <div class="container-fluid">
    <%= page_entries_info visits %>
  </div>

  <div class="card">
    <div class="scroll">
      <table class="form-table">
        <thead>
          <tr>
            <th>Persona</th>
            <th>Fecha</th>
            <th>Comentario</th>
            <% if !Rails.env.production? %>
              <th>Latitud</th>
              <th>Longitud</th>
            <% end %>
            <th>Dirección</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @visits.each do |visit| %>
            <tr>
              <% if visit.person.nil? %>
                <td>Sin persona</td>
              <% else %>
                <td><%= visit.person.nombre  %></td>
              <% end %>
              <td><%= visit.fecha.to_date() %></td>
              <td><%= visit.descripcion %></td>
              <% if !Rails.env.production? %>
                <td><%= visit.latitud %></td>
                <td><%= visit.longitud %></td>
              <% end %>
              <td><%= visit.direccion %></td>
              <td>
                <%=
                  render 'layouts/acciones',
                  current_user: current_user,
                  edit_path: edit_visit_path(visit, :person_id => params[:person_id]),
                  delete_path: RolDataAccess.puede_borrar_visita(current_user) ? visit_path(visit, :person_id => params[:person_id]) : nil
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= will_paginate visits %>

</div>

app/views/visits/edit.html.erb
<h2 class="sub-header">Visita</h2>

<%= render 'form', puede_editar: RolDataAccess.puede_editar_visita(current_user) %>

app/views/visits/index.html.erb
<h2 class="sub-header">Visitas</h2>

<%= render 'layouts/filtros_completo' %>

<%= render 'visits/list', visits: @visits %>

<%= render 'layouts/new_button', :label => 'Nueva visita', :path => new_visit_path(:person_id => params[:person_id]) %>

app/views/visits/index.js.erb
<% js = escape_javascript(render(partial: 'visits/list', locals: { visits: @visits })) %>
$("#filterrific_results").html("<%= js %>");

app/views/visits/new.html.erb
<h2 class="sub-header">Nueva visita</h2>

<%= render 'form', puede_editar: RolDataAccess.puede_editar_visita(current_user) %>