config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    post 'areas/download' => 'areas#download'
    post 'areas/upload' => 'areas#upload'
    post 'zones/download' => 'zones#download'
    post 'zones/upload' => 'zones#upload'
    post 'visits/download' => 'visits#download'
    post 'visits/upload' => 'visits#upload'
    post 'pedidos/download' => 'pedidos#download'
    post 'pedidos/upload' => 'pedidos#upload'
    post 'people/download' => 'people#download'
    post 'people/upload' => 'people#upload'
    post '2.0/personas' => 'people#list'
    post '2.0/persona' => 'people#get'
    post '2.0/visitas' => 'visits#list'
    post '2.0/visita' => 'visits#get'
  end

  resources :notificaciones
  resources :auditoria
  resources :users
  resources :areas
  root 'mapa#index'

  get 'acceso_denegado', to: redirect('/401.html')
  get 'falta_confirmacion', to: redirect('/falta_confirmacion.html')

  get 'common/update_zonas_filter', as: 'update_zonas_filter'
  get 'common/update_personas', as: 'update_personas'
  get 'common/update_pedidos_pendientes', as: 'update_pedidos_pendientes'
  get 'common/edit_pedido_modal/:id' => 'common#edit_pedido_modal', as: 'edit_pedido_modal'


  get 'people/update_zonas', as: 'update_zonas'

  # No existe en el código el dataAccess relacionado
  # post 'visits/mobRecibirVisitasDesde' => 'visits#mobRecibirVisitasDesde'

  get 'visits/getDireccion' => 'visits#getDireccion'
  get 'visits/getCoordenadas' => 'visits#getCoordenadas'

  get 'mapa/mostrar' => 'mapa#mostrar'
  get 'mapa/mobMapaPersonas' => 'mapa#mobMapaPersonas'

  resources :visits
  resources :people
  resources :zones
  resources :mapa
  resources :pedidos
  resources :departamentos
  resources :estados
  resources :instituciones
  resources :eventos

  get 'informes' => 'informes#index'
  get 'informes/voluntarios' => 'informes#voluntarios'
  get 'informes/personas' => 'informes#personas'
  get 'informes/cumpleanios' => 'informes#cumpleanios'
  get 'informes/visitas' => 'informes#visitas'
end

app/controllers/instituciones_controller.rb
class InstitucionesController < ApplicationController
    before_action :set_institucion, only: [:show, :edit, :update, :destroy]
    before_action :puede_crear_institucion, only: [:create]
    before_action :puede_editar_institucion, only: [:update]
    before_action :puede_borrar_institucion, only: [:destroy]

  def index
    @filterrific = initialize_filterrific(
      Institucion,
      params[:filterrific],
      select_options: {
        #with_area_id: Institucion.options_for_select
      },
      default_filter_params: {}
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @instituciones = @filterrific.find.includes(:institucion_tipo).activas.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /instituciones/1
  # GET /instituciones/1.json
  def show
  end

  # GET /instituciones/new
  def new
    @institucion = Institucion.new
  end

  # GET /instituciones/1/edit
  def edit
  end

  # POST /instituciones
  # POST /instituciones.json
  def create
    @institucion = Institucion.new(institucion_params)
    @institucion.state = State.find_by_nombre('Actualizado')

    respond_to do |format|
      if @institucion.save
        AuditoriaDataAccess.log current_user, Auditoria::ALTA, Auditoria::INSTITUCION, @institucion
        format.html { redirect_to instituciones_url, notice: 'Institución creada correctamente.' }
        format.json { render :show, status: :created, location: @institucion }
        format.js { render :show, status: :created, location: @institucion }
      else
        format.html { render :new }
        format.json { render json: @institucion.errors, status: :unprocessable_entity }
        format.js   { render json: @institucion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instituciones/1
  # PATCH/PUT /instituciones/1.json
  def update
    respond_to do |format|
      if @institucion.update(institucion_params)
        AuditoriaDataAccess.log current_user, Auditoria::MODIFICACION, Auditoria::ZONA, @institucion
        format.html { redirect_to instituciones_url, notice: 'Institución actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @institucion }
      else
        format.html { render :edit }
        format.json { render json: @institucion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instituciones/1
  # DELETE /instituciones/1.json
  def destroy
    InstitucionDataAccess.borrar_logico(@institucion, current_user)
    respond_to do |format|
      format.html { redirect_to instituciones_url, notice: 'Institución borrada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institucion
      @institucion = Institucion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institucion_params
      params.require(:institucion).permit(:nombre, :codigo_postal, :contacto, :telefono, :direccion, :descripcion, :latitud, :longitud, :institucion_tipo_id)
    end
end

app/views/instituciones/_form.html.erb
<% puede_editar ||= false %>
<% disabled = !puede_editar %>

<%= form_for(@institucion, :html => {:class => 'form-horizontal container-fluid'} ) do |f| %>
  <%= render 'shared/errors', obj: @institucion %>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :nombre, :disabled => disabled %>
      <%= f.label :nombre, class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.collection_select :institucion_tipo_id, InstitucionTipo.all, :id, :nombre, {:include_blank => true}, {:disabled => disabled} %>
      <%= f.label :institucion_tipo_id, "Tipo", class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_area :descripcion, class:"materialize-textarea", :disabled => disabled %>
      <%= f.label :descripcion, class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :direccion, :disabled => disabled %>
      <%= f.label :direccion, 'Dirección', class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :contacto, :disabled => disabled %>
      <%= f.label :contacto, class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :telefono, :disabled => disabled %>
      <%= f.label :telefono, class: "active" %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :codigo_postal, :disabled => disabled %>
      <%= f.label :codigo_postal, 'Código postal', class: "active" %>
    </div>
  </div>
 
  <%= f.hidden_field :latitud, class: "form-control", :disabled => disabled %>
  <%= f.hidden_field :longitud, class: "form-control", :disabled => disabled %>

  <div class="form-group">
    <%= f.label 'Ubicación', class: "col-md-1 control-label", for: "googleMapPersona" %>
    <div class="col-md-10">
      <div id="googleMapPersona" class="mapaUbicacionPersona"></div>
    </div>
  </div>
  
  <%= render 'layouts/buttons_submit', path: path, f: f, mostrar_aceptar: puede_editar %>

<% end %>

<script defer>
  loadMapaScript('cargarUbicacionInstitucion');
</script>

app/views/instituciones/_list.html.erb
<div id="filterrific_results">

  <div class="container-fluid">
    <%= page_entries_info instituciones %>
  </div>

  <div class="card">
    <div class="scroll">
      <table class="form-table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Tipo</th>
            <th>Dirección</th>
            <th>Contacto</th>
            <th>Teléfono</th>
            <th>Código postal</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @instituciones.each do |institucion| %>
            <tr>
              <td><%= institucion.nombre %></td>
              <td><%= institucion.descripcion %></td>
              <% if institucion.institucion_tipo.nil? %>
                <td></td>
              <% else %>
                <td><%= institucion.institucion_tipo.nombre %></td>
              <% end %>
              <td><%= institucion.direccion %></td>
              <td><%= institucion.contacto %></td>
              <td><%= institucion.telefono %></td>
              <td><%= institucion.codigo_postal %></td>
              <td>
                <%=
                  render 'layouts/acciones',
                  current_user: current_user,
                  institucion_id: institucion.id,
                  edit_path: edit_institucion_path(institucion),
                  delete_path: RolDataAccess.puede_borrar_institucion(current_user) ? institucion : nil
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= will_paginate instituciones %>

</div>

app/views/instituciones/edit.html.erb
<h2 class="sub-header">Institución</h2>

<%= render 'form', :path => instituciones_path, puede_editar: RolDataAccess.puede_editar_institucion(current_user) %>

app/views/instituciones/index.html.erb
<h2 class="sub-header">Instituciones</h2>

<%= render 'instituciones/list', instituciones: @instituciones %>

app/views/instituciones/new.html.erb
<h2 class="sub-header">Nueva institución</h2>

<%= render 'form', :path => instituciones_path, puede_editar: RolDataAccess.puede_crear_institucion(current_user) %>