config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    post 'areas/download' => 'areas#download'
    post 'areas/upload' => 'areas#upload'
    post 'zones/download' => 'zones#download'
    post 'zones/upload' => 'zones#upload'
    post 'visits/download' => 'visits#download'
    post 'visits/upload' => 'visits#upload'
    post 'pedidos/download' => 'pedidos#download'
    post 'pedidos/upload' => 'pedidos#upload'
    post 'people/download' => 'people#download'
    post 'people/upload' => 'people#upload'
    post '2.0/personas' => 'people#list'
    post '2.0/persona' => 'people#get'
    post '2.0/visitas' => 'visits#list'
    post '2.0/visita' => 'visits#get'
  end

  resources :notificaciones
  resources :auditoria
  resources :users
  resources :areas
  root 'mapa#index'

  get 'acceso_denegado', to: redirect('/401.html')
  get 'falta_confirmacion', to: redirect('/falta_confirmacion.html')

  get 'common/update_zonas_filter', as: 'update_zonas_filter'
  get 'common/update_personas', as: 'update_personas'
  get 'common/update_pedidos_pendientes', as: 'update_pedidos_pendientes'
  get 'common/edit_pedido_modal/:id' => 'common#edit_pedido_modal', as: 'edit_pedido_modal'


  get 'people/update_zonas', as: 'update_zonas'

  # No existe en el código el dataAccess relacionado
  # post 'visits/mobRecibirVisitasDesde' => 'visits#mobRecibirVisitasDesde'

  get 'visits/getDireccion' => 'visits#getDireccion'
  get 'visits/getCoordenadas' => 'visits#getCoordenadas'

  get 'mapa/mostrar' => 'mapa#mostrar'
  get 'mapa/mobMapaPersonas' => 'mapa#mobMapaPersonas'

  resources :visits
  resources :people
  resources :zones
  resources :mapa
  resources :pedidos
  resources :departamentos
  resources :estados
  resources :instituciones
  resources :eventos

  get 'informes' => 'informes#index'
  get 'informes/voluntarios' => 'informes#voluntarios'
  get 'informes/personas' => 'informes#personas'
  get 'informes/cumpleanios' => 'informes#cumpleanios'
  get 'informes/visitas' => 'informes#visitas'
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :state
  validates :nombre, presence: true
  scope :activos, -> { where.not(state_id: 3).order(:nombre) }

    def self.options_for_select
        activos.order('LOWER(nombre)').map { |e| [e.nombre, e.id] }
    end

    def getDescripcionAuditoria
        return "Nombre: #{nombre}"
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]
  before_action :puede_editar_estado

  def index
    @estados = Estado.activos
    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
    end
  end

  def new
    @estado = Estado.new
  end

  def edit
  end

  def show
  end

  def create
    @estado = Estado.new(estado_params)
    @estado.state = State.find_by_nombre('Actualizado');

    respond_to do |format|
      if @estado.save
        AuditoriaDataAccess.log current_user, Auditoria::ALTA, Auditoria::ESTADO, @estado
        format.html { redirect_to estados_url, notice: I18n.t('common.exito.creacion_estado') }
        format.json { render :show, status: :created, location: @estado }
        format.js { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
        format.js   { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @estado.update(estado_params)
        AuditoriaDataAccess.log current_user, Auditoria::MODIFICACION, Auditoria::ESTADO, @estado
        format.html { redirect_to estados_url, notice: I18n.t('common.exito.actualizacion_estado') }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    EstadoDataAccess.borrar_logico(@estado, current_user)
    respond_to do |format|
      format.html { redirect_to estados_url, notice: I18n.t('common.exito.borrado_estado') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nombre)
    end
end

app/views/estados/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<% puede_editar ||= false %>
<% disabled = !puede_editar %>

<%= form_for(@estado, remote: remote, :html => {'data-model' => 'estado', :class => 'form-horizontal container-fluid'} ) do |f| %>
  <%= render 'shared/errors', obj: @estado %>

  <%= render 'layouts/text_field', name: :nombre, label_name: :nombre, f: f, remote: remote, puede_editar: puede_editar %>

  <%= render 'layouts/buttons_submit', path: estados_path, f: f, remote: remote, mostrar_aceptar: puede_editar %>

<% end %>

app/views/estados/_list.html.erb
<div class="card">
  <div class="scroll">
    <table class="form-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <% if RolDataAccess.puede_editar_estado(current_user) %>
            <th>Acciones</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @estados.each do |estado| %>
          <tr>
            <td><%= estado.nombre %></td>
            <td>
              <%=
                render 'layouts/acciones',
                current_user: current_user,
                edit_path: RolDataAccess.puede_editar_estado(current_user) ? edit_estado_path(estado) : nil,
                delete_path: RolDataAccess.puede_editar_estado(current_user) ? estado : nil
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/estados/edit.html.erb
<h2 class="sub-header"><%= t("activerecord.models.estado.one") %></h2>

<%= render 'form', puede_editar: RolDataAccess.puede_editar_estado(current_user) %>

app/views/estados/index.html.erb
<h2 class="sub-header"><%= t("activerecord.models.estado.other") %></h2>

<%= render 'list' %>

<% if RolDataAccess.puede_editar_estado(current_user) %>
  <%= render 'layouts/new_button', :label => t("common.nuevo_estado"), :path => new_estado_path %>
<% end %>

app/views/estados/new.html.erb
<h2 class="sub-header"><%= t("common.nuevo_estado") %></h2>

<%= render 'form', puede_editar: RolDataAccess.puede_editar_estado(current_user) %>