config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    post 'areas/download' => 'areas#download'
    post 'areas/upload' => 'areas#upload'
    post 'zones/download' => 'zones#download'
    post 'zones/upload' => 'zones#upload'
    post 'visits/download' => 'visits#download'
    post 'visits/upload' => 'visits#upload'
    post 'pedidos/download' => 'pedidos#download'
    post 'pedidos/upload' => 'pedidos#upload'
    post 'people/download' => 'people#download'
    post 'people/upload' => 'people#upload'
    post '2.0/personas' => 'people#list'
    post '2.0/persona' => 'people#get'
    post '2.0/visitas' => 'visits#list'
    post '2.0/visita' => 'visits#get'
  end

  resources :notificaciones
  resources :auditoria
  resources :users
  resources :areas
  root 'mapa#index'

  get 'acceso_denegado', to: redirect('/401.html')
  get 'falta_confirmacion', to: redirect('/falta_confirmacion.html')

  get 'common/update_zonas_filter', as: 'update_zonas_filter'
  get 'common/update_personas', as: 'update_personas'
  get 'common/update_pedidos_pendientes', as: 'update_pedidos_pendientes'
  get 'common/edit_pedido_modal/:id' => 'common#edit_pedido_modal', as: 'edit_pedido_modal'


  get 'people/update_zonas', as: 'update_zonas'

  # No existe en el código el dataAccess relacionado
  # post 'visits/mobRecibirVisitasDesde' => 'visits#mobRecibirVisitasDesde'

  get 'visits/getDireccion' => 'visits#getDireccion'
  get 'visits/getCoordenadas' => 'visits#getCoordenadas'

  get 'mapa/mostrar' => 'mapa#mostrar'
  get 'mapa/mobMapaPersonas' => 'mapa#mobMapaPersonas'

  resources :visits
  resources :people
  resources :zones
  resources :mapa
  resources :pedidos
  resources :departamentos
  resources :estados
  resources :instituciones
  resources :eventos

  get 'informes' => 'informes#index'
  get 'informes/voluntarios' => 'informes#voluntarios'
  get 'informes/personas' => 'informes#personas'
  get 'informes/cumpleanios' => 'informes#cumpleanios'
  get 'informes/visitas' => 'informes#visitas'
end

app/controllers/notificaciones_controller.rb
class NotificacionesController < ApplicationController
  include ApplicationHelper
  before_action :set_notificacion, only: [:show, :edit, :update, :destroy]
  before_action :puede_ver_notificaciones

	def index
    @filterrific = initialize_filterrific(
      Notificacion,
      params[:filterrific],
      default_filter_params: {}
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @notificaciones = @filterrific.find.includes(:frecuencia_tipo, :roles).activas.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /notificacion/new
  def new
    @notificacion = Notificacion.new
    @notificacion.setup_roles!
  end

  # GET /notificacion/1/edit
  def edit
    @notificacion.setup_roles!
  end

  # POST /notificacion
  # POST /notificacion.json
  def create
    @notificacion = Notificacion.new(notificacion_params)
    @notificacion.state = State.find_by_nombre('Actualizado')
    @notificacion.sacar_minutos
    @notificacion.prox_envio = @notificacion.fecha_desde
    @notificacion.finalizada = false
    respond_to do |format|
      if @notificacion.save
        AuditoriaDataAccess.log current_user, Auditoria::ALTA, Auditoria::NOTIFICACION, @notificacion
        format.html { redirect_to notificaciones_url, notice: 'Notificación creada correctamente.' }
        format.json { render :show, status: :created, location: @notificacion }
      else
        @notificacion.setup_roles!
        format.html { render :new }
        format.json { render json: @notificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificacion/1
  # PATCH/PUT /notificacion/1.json
  def update
    respond_to do |format|
      if @notificacion.finalizada || @notificacion.necesitaCalcularProxEnvio(notificacion_params)
        exitoActualziar = @notificacion.update(notificacion_params)
        if @notificacion.finalizada && @notificacion.fecha_desde_en_el_pasado
          exitoActualziar = false
        end
        @notificacion.finalizada = false
        @notificacion.prox_envio = @notificacion.fecha_desde
        if @notificacion.fecha_desde_en_el_pasado
          @notificacion.calcularProxEnvio
        end
      else
        exitoActualziar = @notificacion.update(notificacion_params)
      end
      if exitoActualziar
        @notificacion.sacar_minutos
        @notificacion.save
        AuditoriaDataAccess.log current_user, Auditoria::MODIFICACION, Auditoria::NOTIFICACION, @notificacion
        format.html { redirect_to notificaciones_url, notice: 'Notificación actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @notificacion }
      else
        @notificacion.setup_roles!
        format.html { render :edit }
        format.json { render json: @notificacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificacion/1
  # DELETE /notificacion/1.json
  def destroy
    NotificacionDataAccess.borrar_logico(@notificacion, current_user)
    respond_to do |format|
      format.html { redirect_to notificaciones_url, notice: 'Notificación borrada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacion
      @notificacion = Notificacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificacion_params
      params.require(:notificacion).permit(
        {area_ids: []},
        :titulo,
        :subtitulo,
        :fecha_desde,
        :fecha_hasta,
        :descripcion,
        :frecuencia_cant,
        :frecuencia_tipo_id,
        {rol_ids: []}
      )
    end
end

app/helpers/notificaciones_helper.rb
module NotificacionesHelper
end

app/views/notificaciones/_form.html.erb
<div class="row">
  <%= form_for(@notificacion, :html => {:class => 'col s12'}) do |f| %>
    <%= render 'shared/errors', obj: @notificacion %>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :titulo %>
        <%= f.label :titulo, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :subtitulo %>
        <%= f.label :subtitulo, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :fecha_desde, id: "datetimefrom" %>
        <%= f.label :fecha_desde, 'Fecha Desde', class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :fecha_hasta, id: "datetimeto" %>
        <%= f.label :fecha_hasta, 'Fecha Hasta', class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :descripcion, class:"materialize-textarea" %>
        <%= f.label :descripcion, 'Descripción', class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s4">
        <%= f.collection_select :frecuencia_tipo_id, FrecuenciaTipo.all, :id, :nombre, {:include_blank => false} %>
        <%= f.label :frecuencia_tipo_id, 'Frecuencia', class: "active" %>
      </div>

      <div class="input-field col s4">
        <%= f.text_field :frecuencia_cant %>
        <%= f.label :frecuencia_cant, 'Repeticiones' %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s4">
        <%= f.collection_select :rol_ids, Rol.activos, :id, :nombre, {:include_blank => true}, {multiple: true} %>
        <%= f.label :rol_ids, 'Roles', class: "active" %>
      </div>

      <div class="input-field col s4 offset-s2">
        <%= f.collection_select :area_ids, Area.activas, :id, :nombre, {:include_blank => true}, {multiple: true} %>
        <%= f.label :area_ids, "Sedes", class: "active"%>
      </div>
    </div>

    <%= render 'layouts/buttons_submit', path: notificaciones_path, f: f, remote: false, mostrar_aceptar: RolDataAccess.puede_ver_notificaciones(current_user) %>

  <% end %>
</div>

app/views/notificaciones/_list.html.erb
<div id="filterrific_results">

  <div class="container-fluid">
    <%= page_entries_info notificaciones %>
  </div>

  <div class="card">
    <div class="scroll">
      <table class="form-table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Subtítulo</th>
            <th>Desde</th>
            <th>Hasta</th>
            <th>Prox Notificación</th>
            <th>Frecuencia</th>
            <th>Roles</th>
            <th>Finalizada</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @notificaciones.each do |notificacion| %>
            <tr>
              <td><%= notificacion.titulo %></td>
              <td><%= notificacion.subtitulo %></td>
              <td><%= notificacion.fecha_desde %></td>
              <td><%= notificacion.fecha_hasta if notificacion.frecuencia_tipo.code != FrecuenciaTipo::UNICA %></td>
              <td><%= notificacion.prox_envio %></td>
              <td><%= notificacion.frecuencia %></td>
              <td>
                <% notificacion.roles.each do |rol| %>
                  <%= rol.nombre %>
                <% end %>
              </td>
              <td><%= notificacion.finalizada ? 'Si' : 'No' %></td>
              <td>
                <%=
                  render 'layouts/acciones',
                         current_user: current_user,
                         edit_path: edit_notificacion_path(notificacion),
                         delete_path: notificacion
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= will_paginate notificaciones %>

</div>

app/views/notificaciones/edit.html.erb
<h2 class="sub-header">Notificación</h2>

<%= render 'form' %>

app/views/notificaciones/index.html.erb
<h2 class="sub-header">Notificaciones</h2>

<div class="container-fluid">
  <div class="row">
    <%= form_for_filterrific @filterrific do |f| %>

      <div class="col s2 m3">
        <%= f.text_field(
          :with_titulo,
          class: 'filterrific-periodically-observed form-control',
          placeholder: 'Título'
        ) %>
      </div>

      <div class="col s3 offset-s1">
        <%= f.text_field(
          :fecha_gte,
          placeholder: 'Desde',
          class: "datepicker"
        ) %>
      </div>

      <div class="col s3 offset-s1">
        <%= f.text_field(
          :fecha_lte,
          placeholder: 'Hasta',
          class: "datepicker"
        ) %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'list', notificaciones: @notificaciones %>

<%= render 'layouts/new_button', :label => 'Nueva notificacion', :path => new_notificacion_path %>

<script type="text/javascript">
  $('#filterrific_fecha_gte').datepicker({
    format: 'dd/mm/yyyy',
    language: 'es'
  });
  $('#filterrific_fecha_lte').datepicker({
    format: 'dd/mm/yyyy',
    language: 'es'
  });
</script>

app/views/notificaciones/index.js.erb
<% js = escape_javascript(render(partial: 'list', locals: { notificaciones: @notificaciones })) %>
$("#filterrific_results").html("<%= js %>");

app/views/notificaciones/new.html.erb
<h2 class="sub-header">Nueva notificación</h2>

<%= render 'form' %>